Steam age-HV quests (#34)
* start Gregtech CEU port. replace crafttweaker with groovyscript

* add Primitive Alloy Smelter

* add Coke Oven

* add Industrial Primitive Blast Furnace

* fix Coke Oven recipemap UI. method reference on constructor like CokeOvenUI::new doesn't appear to work in groovy script

* add Heat Exchanger

* add Armor Infuser

* add Chaos Replicator

* add Dragon Egg Replicator

* add Vial Processor

* add Large Powered Spawner

* add Large Vial Processor

* load TJMetaTileEntities.groovy, TJRecipeMapSteamMultiblockController.groovy, TJSteamMultiblockRecipeLogic.groovy before other groovy classes to fix NoClassDefFoundError with groovy cache

* add Hot Iron Ingot

* port quest chapters from steam age to HV

* add File Director - Incremental Mod Updates to manifest.json

* add GregTech Ceu, GCYL CEu, Gregicality Multiblocks, and TJ Additions to File Director

* add metadata hashing in File Director config to validate correct files

* update config and fix Compact Machines 3 crash due to invalid recipe

* update manifest.json and update Cleanroom Relauncher to v1.0.1

* try to inject GregTech CEu early with File Director because the mod has a core mod

* add recipes to items showcased in steam age - hv age quests

* gregify Applied Energistics 2 recipes (not including addons)

* fix pahoehoe lava fluid

* add starmetal alloy material

* fix me covered cables not being gregified